### ISSUE TITLE
schema_design

### ISSUE THREAD

**Issue by shadowd-dev** [Hungry-Coder-byte/Chat-App#1]
Hi.
users table is not found.

**Comment by Hungry-Coder-byte** [comment]
Hi @shadowd-dev,

Below is the table structure for above issue -

CREATE TABLE users
(
  user_id text NOT NULL DEFAULT uuid_generate_v1(),
  username character varying(25) NOT NULL,
  password character varying(50) NOT NULL,
  email character varying(100) NOT NULL,
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_username_key UNIQUE (username)
)
 
I have also updated in schema_design file.

If you get error like **"function uuid_generate_v4() does not exist"** while creating the above table - then first run below query (for postgresql)

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

Thanks
